### ISSUE TITLE
[RadioGroup, CheckboxGroup] Are item ids really useful ?

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#11]
In the current model of Radio and Checkbox components, a key `id` needs to be defined for each item. I am not convinced it is useful. It seems to me that it is redundant with the item index in the `items` list. 

Here is how I evaluate the Checkbox component. I don't use the id.

~~~
ansright,answrong=0,0
for item in checkbox.items:
    if item['content'] in right and item['checked']:
        item['css'] = 'success-state anim-fade'
        ansright+=1
    elif item['content'] in right and not item['checked']:
        item['css'] = 'success-state anim-fade'
        answrong+=1
    elif not (item['content'] in right) and item['checked']:
        answrong+=1
~~~

Here is how I evaluate the Radio component. I do use the id, but only because radio.selection returns the id. If radio.selection returned the index in `items` list instead, I would not need the id.

~~~
score=0
for i in range(len(radio.items)):
    if radio.items[i]['content']==sol:
        radio.items[i]['css'] = 'success-state anim-fade'
        if radio.items[i]['id']==radio.selection:
            score=100
            break
~~~

**Comment by mciissee** [comment]
The id is the right way to identify the items of a RadioGroup and CheckboxGroup components for the following reason:

- using an index cannot work in the case the you want to sort add, remove items dynamically
- using content cannot work if you use dynamically generated content (MathJax content is not the same before and after the evaluation of the exercise for example $\in$ is replaced by an html code when inserted to the HTML).

**Comment by ddoyen** [comment]
When I use a content like `$$ \\in $$` for an item, it does not seem to be altered at any point in the component and the evaluation by content still seems to work.

I agree that id is the proper approach from a technical standpoint.

But standard users will see that as an unnecessary complication. They will want to give a list of contents to the component and then evaluate the answer by content.

Maybe we could work out methods that make ids transparent in some simple cases :
- an initialization of the item list with only a list of contents (ids are generated automatically),
- the content of the selected item.

**Comment by mciissee** [comment]
I'm agree to change the behavior of theses two components to remove the id property but you should discuss it with the author users (AP1 members like @ochampal @oobouillot) that currently use these components actually because their codes will not work anymore.

**Comment by ddoyen** [comment]
Ok, I'll see with them.

**Comment by mciissee** [comment]
Finally I will keep the id property for technical reasons and to keep consistency with MatchList and SortList component which share the same properties.

SortList and MatchList `id` property cannot be set as the `content` property for the reasons I explained above (dynamic html, MathJax...) so I will keep this property for the RadioGroup and CheckBoxGroup also.
