### ISSUE TITLE
[RadioGroup] Selected item does not remain selected after validation

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#12]
The item selected in a RadioGroup component does not remain selected after the answer is submitted. It should be.

**Comment by mciissee** [comment]
Can you give a link to an exercise with this behavior because the selected item should and is still selected after a submit on my side.

**Comment by ddoyen** [comment]
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/template/radio.pl

**Comment by mciissee** [comment]
I tested the component on Firefox 60.9.0esr 64 bits (the version installed for the desktops at the university), Chrome and Safari and the selection is persisted after the submit.

**Comment by mciissee** [comment]
This issue cannot be reproduced so I will close it for now
