### ISSUE TITLE
[MathDrawer] Change of name

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#13]
I'm not satisfied with the name of the MathDrawer component.

- First, it does not make clear that it is an interactive geometry tool. It is not just a plotting/drawing tool.
- Secondly, it won't be the only geometry/plotting component in PL (we will probably integrate Geogebra one day).

For theses two reasons, I suggest to rename the component as `JSXGraph`.

**Comment by mciissee** [comment]
I'm agree to edit the name of the component since the component is used only by you for instance. I will let you know to edit your exercises after the update
