### ISSUE TITLE
New components : Molecule viewer and Molecule editor

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#15]
Two essential components for chemistry :

- Molecule viewer : JSMol (https://sourceforge.net/projects/jsmol/)
- Molecule editor : JSME (https://peter-ertl.com/jsme/index.html)

**Comment by mciissee** [comment]
As for the GeoGebra component #14 I suggest you to specify the list of properties that the component should expose.

I will create and readme file later to explain how to request new component.

**Comment by ddoyen** [comment]
After some research, I suggest to consider also Kekule.

http://partridgejiang.github.io/Kekule.js/
https://github.com/partridgejiang/Kekule.js/tree/master/src

**Comment by ddoyen** [comment]
Here is a demo for the molecule editor.

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Chemistry/testcomp/kekuleEditor.pl

**Name:** KekuleEditor

**Properties.**

**renderConfigs:** see http://partridgejiang.github.io/Kekule.js/documents/tutorial/content/composer.html#more-configurations

**editorConfigs:** see http://partridgejiang.github.io/Kekule.js/documents/tutorial/content/composer.html#more-configurations

**smiles:** [smiles](https://en.wikipedia.org/wiki/Simplified_molecular-input_line-entry_system) string of the molecule drawn in the editor

**Comment by ddoyen** [comment]
Here is a demo for the molecule viewer.

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Chemistry/testcomp/KekuleViewer.pl

**Comment by mciissee** [comment]
I tried to implement Kekule.js as a component and there is some issues with the lib.

- It is not designed to be a custom web element.
- It doesn't work on some browsers (Firefox for example)
...

I suggest you to search an alternative to this lib and submit a new issue using the issue templates.
