### ISSUE TITLE
input number

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#17]
Traceback (most recent call last):
  File "grader.py", line 44, in 
    exec(add_try_clause(dic['evaluator'], StopEvaluatorExec), dic)
  File "", line 5, in 
ValueError: invalid literal for int() with base 10: '2,5'

y a moyen de faire quelque chose pour celaet pour le cas ou il n'y a pas de réponse de l'utilisateur. 
Que cela fasse pas planter le grader.

**Comment by mciissee** [comment]
after the requests #8 and #9 you have to check by yourself the value property

if 'value' in component:
   ...

**Comment by nimdanor** [comment]
See comment in #9
