### ISSUE TITLE
Les Tabs

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#18]
Peut faire que tabulation fasse passer d'un champ de réponse à un autre.
Dans cet exo tab cela fait passer d'une opérande à l'autre c'est bof.
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/python/AP1-1920/drafts/Theme1-bases-imperatif/expressionaleatoires.pl

**Comment by mciissee** [comment]
Les tabs fonctionnent pour le composant le problème de cet exercise est particulier.

Lorsque vous appuyez sur la touche Tab, Javascript cherche a donner le focus au prochain l'element le plus proche dans votre cas le plus proche après un champs de saisie est un element MathJax.

Si vous ne voulez pas ce comportement, vous devez retirer le MathJax de votre exercise ` $% {{op1[loop.index0]}} %$ {{ope[loop.index0]}} $%` en retirant les **$%**

**Comment by nimdanor** [comment]
Excellent
