### ISSUE TITLE
[DragDrop] Mechanism to display correction

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#19]
In the current version of DragDrop components, one can change the color of the drop boxes to mark if it's right or wrong (using `css` property), but there is no specific mechanism to display a correction.

I suggest to add a new property `tooltip` (and maybe also a property `css-tooltip`) to `drop` components. The content of `tooltip` (if not empty) will be displayed as a tooltip when the mouse is over the drop box (or when the drop box is touched on touch screen devices).

In practice, this new property will be used to display a correction at the end of an exercise.

**Comment by mciissee** [comment]
This feature is already implemented you can set the `content` property of the DragDrop component inside your grader to display a correction.

You can also set the property `disabled` to `True` as for the majority of the components to disabled user interaction.

**Comment by mciissee** [comment]
I suggest you to use the solution above or think about another one I tried to add replace the content when the mouse over the component and there is many bugs and this is not technically possible on mobile device because the hover event is canceled by the drag event.
