### ISSUE TITLE
[MathInput] Predefined virtual keyboards

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#2]
I open this issue to discuss the predefined virtual keyboards for the MathInput component.

For now, I suggest the following predefined keyboards:
- Elementary
- Relations (equations, inequalities)
- Sets
- Functions
- Complexes

Their JSON definition is provided in Yggdrasil/Mathematics/template/mathexpr.pl

I don't know if it's easy to add these new keyboards to the MathInput component, but it would solve my issue with keyboards (https://github.com/PremierLangage/premierlangage/issues/307). Problem I need to solve before September 5... :-)

**Comment by mciissee** [comment]
I this can be closed? Important even for the next release I suggest you to keep your strategy to load the config from a json file.
