### ISSUE TITLE
Some precisions/suggestions for sorted list

### ISSUE THREAD

**Issue by nborie** [PremierLangage/components#20]
I did play with sorted list here : 

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/C/exercices/program/compilation.pl

Some comments/suggestions 

* Same as Match list, I did add some vertical space between the displayed text and the form with some extracss. It could be fine the default behavior contain something realizing this margin.

* Code in back-ticks seems always interpreted as Latex code. I would love put Python or C code inside some content champ of some component. However, if only one kind of code can appear, I validate the choice of latex (even I do computer science...). If there is already special syntax to include code C or Python, please tell me.

* It could be fine if the default behavior of sorted list put the content of each cell centered. 

* It seems to me that element inside component (content in Match List, content in Sorted List) do not support markdown. html work inside these champs.

* It seems to me that feedback does not support markdown. html inside feedback work well.

* I did just realize that title do not support markdown either. Perhaps all this is related to playexo only and not component. Anyway, in a perfect word, all content containing instruction, advise, text or feedback should accept markdown.

**Comment by mciissee** [comment]
> Same as Match list, I did add some vertical space between the displayed text and the form with some extracss. It could be fine the default behavior contain something realizing this margin.

The margin is controlled by playexo it's outside of component scope we will add the default margin for the next release.

> Code in back-ticks seems always interpreted as Latex code. I would love put Python or C code inside some content champ of some component. However, if only one kind of code can appear, I validate the choice of latex (even I do computer science...). If there is already special syntax to include code C or Python, please tell me.

I implemented markdown support for MatchList, SortList, RadioGroup, CheckboxGroup components so the code inside a back-ticks should work now (or later depending on the latency of the CDN). TextComponent support only text content for technical reason.

> It could be fine if the default behavior of sorted list put the content of each cell centered.
Done but this type of behavior should be controlled by a teacher using css.

> It seems to me that element inside component (content in Match List, content in Sorted List) do not support markdown. html work inside these champs.

Done


> I did just realize that title do not support markdown either. Perhaps all this is related to playexo only and not component. Anyway, in a perfect word, all content containing instruction, advise, text or feedback should accept markdown.

Displaying of title, form, text and feedback is controlled by playexo outside of components. The component framework is detached from PL.

**Comment by mciissee** [comment]
Is this one can be closed @nborie?

**Comment by nborie** [comment]
It is OK for me... I did test and enjoyed the updates some days ago. Nothing more for me is needed on this one.

**Comment by mciissee** [comment]
Perfect
