### ISSUE TITLE
New component : hints

### ISSUE THREAD

**Issue by nborie** [PremierLangage/components#21]
This is not something simple since all teacher won't be all agree on the way this kind of component should work.

The goal is to provide some hints to help the student during the exercise. For the hints, something like a collection of the following should be fine.

        {
            "id": string, // id of the item.
            "content": string, // HTML content of the hint.
            "css": string, // optional css classes of the component separated by a space.
        } 

The hard part is the following one : determine how to trigger an hint. The easy way is to model a component which provide no hint at the first validate, thus provide hint of the first id, thus every time the grade is not perfect, add a hint. All activated hint should be displayed at the end of the text, just before the form.

This could be a nice component for a first run. Currently, PL resources have a lack of adapted or personalized feedback. 

In a perfect future, a nice trigger of hint for computer science is the following one : detect a non presence of a key word. Example : the student code do not contains 'strlen'. Thus this activate a hint : "Vous devriez peut-être utiliser la fonction strlen qui permet de récupérer la longueur d'une chaîne."

But this is for the future... hints by attempts is a nice first way of providing help even it is not very smart. 

Perhaps trigger could be a component (to force the use of some keywords, to prohibit some other keywords, ...). Perhaps hints in this context become a couple (trigger, callback). So if the student activate the trigger, the callback activate the pedagogical feedback.

**Comment by mciissee** [comment]
This could be implemented quickly any remarks before I start to create the component @nimdanor ?

**Comment by nimdanor** [comment]
Who is responsible for the number of trys ? 
This should be done every time by the sandbox no ?
But the sandbox doesn't know the pl, there is no need of a pl ... 
Can the back office (not the sandbox) take care of the number of trys ? @qcoumes 
With a clear syntax for the grade = 0 to 100 one try (negative grade no try).
And the value update in the pl/activity/sessions? (@Pavell94000 )

**Comment by nimdanor** [comment]
the hint macnisem of khan academie is that there is a button to get the hint in the case the student uses the hint he doesn't get the credits for the exercise. 
The hint is progressive unfolding progressively the help and solution to the exercise.
We should take our inspiration there.

**Comment by nborie** [comment]
I did try it just know on khan academy....

Khan proposes a video without a loss of point, then if it is not enough, Khan proposes hints. Khan asks for confirmation before displaying a hint since the user won't validate its learning when he uses hints.

We can go for the same behavior... I would say that the grader should still rule the grade regarding the uses of hints. 

With this, hints would be a ordered collection of actionable hints, not activated at the beginning and positioned between 'text' and 'form'. Since green means good and red means bad, hints could use the orange color. The component should provide and easy way to get the level of hints activated by the student (which is really not an hard point to implement).

Simple and efficient, this kind of component could normally be compatible with any exercise... Like the debug mode, it could be fine to keep a Boolean to activate/deactivate the hints (allowing to re-use exercise with hints in exam mode...).

**Comment by mciissee** [comment]
I added new component [CountDown](https://pl.u-pem.fr/components/countdown).

You can play with it and tell me what you think about it.

Since I cannot modify the python side of the components dynamically, the component is not named.  You must use the full syntax of the framework to create instead of =: operator like I did in my example

**Comment by mciissee** [comment]
Any news about this?

**Comment by nimdanor** [comment]
Very good stuff !! 
i love it !

**Comment by mciissee** [comment]
Nice ! I close this one.
