### ISSUE TITLE
Components text : a question and a potential doc update

### ISSUE THREAD

**Issue by nborie** [PremierLangage/components#22]
I am playing with the component text. 

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Languages/French/pronoms_personnels.pl

I did try to re-implement the evaluator using a contains Python test (with 'in') since I want to detect word inside a finite list that I can encode 
    
    pronoms = ['je', 'tu', 'il', ..., 'moi', 'toi', 'lui', 'eux', ...]

I understand that selected words by the user is an iterable 

    for e in selectable.selections:

I did see that 'index' or 'css' are key of object e (the selected item...). But how can I get the word, the string word selected by the user ? I would love doing something like

    if e['content'] in pronoms:

It seems to me that the documentation do not specify the available keys of object e...

**Comment by ddoyen** [comment]
I also suggest to rename this component to something like `SelectWord`, `SelectText`, `TextSelect`,...

It would be more telling.

**Comment by mciissee** [comment]
I modified the component to add `word` property to the component and updated the doc

**Comment by mciissee** [comment]
> It seems to me that the documentation do not specify the available keys of object e...
This is displayed on the Representation section
```
{
    "index": number, // index of the item.
    "word": string, // the selected word.
    "css": string, // optional css classes of the component separated by a space.
}
```

> I also suggest to rename this component to something like SelectWord, SelectText, TextSelect,...
I'm agree with this suggestion but I cannot update dynamically the python side of the components for now so this will be done later as for new component requests and all the other renaming requests

**Comment by nborie** [comment]
I did update my code using this component. Everything is ok on my side !
