### ISSUE TITLE
New component : limit time to answer

### ISSUE THREAD

**Issue by nborie** [PremierLangage/components#23]
I do not know so much around angular...

Anyway, can you dealt with limit time to answer at component level during playexo 

* Using the component, the teacher provide a limit time in seconds.
* The component add a kind of graphical countdown just next to validate button.
* If the countdown reach zero, the validate button is hit automatically.
* The component provide an extra variable during the grader (something like "remaining_time"), this will allows the grader to detect fast or slow student... The grader has the responsibility to use or not this extra information. If the grader returns -1 (refuse to grade due to not filled forms), the -1 become 0 for time exceeded (this last thing would make compatible any exercise to this component if technically possible...).

This component, if angular - js compatible would be a very nice inter step on the road to exam activity.

**Comment by mciissee** [comment]
Basically Angular is a Javascript frontend framework. It is used mainly to create Single Page Applications (the website is divided into multiples, separated, encapsulated parts called components that can update themselves without the need to refresh the whole page).
On the other side Angular allow to create custom web elements (custom html tags) which can be used like native elements (h1, div, span...) with any web project without the need to depend on Angular framework. PL components use this second capability of Angular.

So the limit time to answer could be a component in PL but you should see with @nimdanor and @Pavell94000 if they have another plan to implement this type of activity before I introduce this component. 


Each component can update itself this
> If the grader returns -1 (refuse to grade due to not filled forms), the -1 become 0 for time exceeded (this last thing would make compatible any exercise to this component if technically possible...)

I didn't understand this sentence. Is the component responsible to handle the grader response or the activity?

**Comment by nborie** [comment]
Originally, we(D.R., N.B.) did think that customization like time restriction was a kind of extra-condition that could be applied to any exercise. This kind of general extra-conditions make us think about Python decorators ( something like @time_limit(120sec) to add somewhere in a .pl file ).

But currently, the components  of PL is a kind of collection of mini frameworks increasing the UI/UX and customizing playexo without re-implementing playexo and also independent from playexo. And this is very important... This is exactly what we want when we set time restriction to a an atom (a single .pl file). 

After, if activities need time limits. It is for me another need, different... An activity could have time limit but the .pl inside no time limit, An activity could have no time limit but as it contains a memory exercise, could contains some exercises with time limits. All combinations are possible.

In my opinion (@Pavell94000, @nimdanor), dealing with limit times of A SINGLE EXERCISE inside the component is a nice localization since it just customize playexo in a independent side-framework . Generally, any decision making playexo lighter is a good decision. 

I try now to be more meaningful with that :
> If the grader returns -1 (refuse to grade due to not filled forms), the -1 become 0 for time 
> exceeded (this last thing would make compatible any exercise to this component if technically 
> possible...)

In an ideal world, for all well working exercise FOO.pl, one could do a new file FOO_time.pl

    extends = FOO.pl
    time.limit = 120
    {{ time | component }}
    
Such that FOO_time is exactly the same exercise but with a time limit of 2 minutes. But, currently, we did encourage to grade with -1 when a grader "do not want to grade now". The main reason why "a grader do not want to grade" is that the student do not filled properly the form. This a nice behavior for exercise FOO.pl (naturally, we give a second chance to the student...). But in FOO_time.pl, if the countdown reach zero and the student did not fill properly the form, we do not want to give a second chance. So the not filled form is a student mistake when time limit is activated. Then, in a perfect world, this component limit time intercept the grade and if this last one is -1 and time has been exceeded, transform the -1 into 0.

Another possible design is that the student MUST clic on validate before the count down reach zero otherwise the usual grader is never called but the component set a grade of -2 (time exceeded error) for the exercise. 

In the first choice, all current exercises become time limit compatible. In the second design, it allows teacher and activities to use the -2 during global notation...

**Comment by mciissee** [comment]
I added new component [CountDown](https://pl.u-pem.fr/components/countdown).


You can play with it and tell me what you think about it.

As for the issue #21 you must use the full syntax instead of =: operator to create the component for now.

**Comment by nborie** [comment]
This is a first play with it : 

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Languages/English/irregular_verbs.pl

And seriously, this is already addicting me.... Wait a little before closing this ticket, I would like to play with programming and limit time ( game like code golf : validate tests with least characters you can do in 5 minutes for example ).

I will post my experimentation with this component here...

**Comment by nborie** [comment]
I am trying to test interoperability of some component....

I am currently mixing three components : input (a text) + hint + countdown. This is like the famous TV game show for retired people "Question pour un champion". In the last games of "Question pour un champion", you have a countdown from 4 to 1. During each step, the TV host tell an hint. If one the player push the buzzer, he can try to answer. If you answer with less hint (at the beginning of the question, you won more points...).

So I am trying to define an action registered in the count down component to activate an hint automatically each 5 seconds... This is already too much for me and my knowledge of JS. This is here 

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/Games/pression_question.pl

In particular, I am pretty sure that this code is not good

    autoHint==#|js|
    // This should click on hint 
    const btn = document.querySelector('.c-hint'); // I am dreamming...
    btn.click()
    ==

Could you help me ? This kind of mix of functionnalities would be a good evidence to illustrate the good/bad design of components (use countdown to auto trigger hints....). I also did not manage to deactivate hints confirmation dialog box...

**Comment by mciissee** [comment]
I fixed your exercise you [here](https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/ComputerScience/Games/pression_question.pl) with the following code
```
autoHint==#|js|
// find the node c-hint inside the dom
// we use direclty the selector c-hint since
// we know that there is only one element on the page
// with the selector c-hint. For an exercise where
// there is multiple components of the same type example multiple hints.
// the argument of querySelector should be the string '[cid=THE_CID_OF_THE_COMPONENT]'
// in this way the function will search the element on the page with the attribute
// cid = THE_CID_OF_THE_COMPONENT.
// As explained from the doc when you write {{ hint|component }} the framework will
// replace it with <c-hint cid="{{ hint.cid }}"></hint>. If you replace the sugar syntactic version
// by the generated version you will get the same behavior.
const hint = document.querySelector('c-hint');

if (hint.consumedCount < hint.items.length) {
    hint.items.forEach(e => e.css = ''); // disable the animations of all the elements
    const item = hint.items[hint.consumedCount++];
    item.consumed = true;
    // animate the new hint animation api is documented at (https://pl.u-pem.fr/components/css-doc)
    item.css = 'animated pulse infinite'; // animate the new hint.
}
==
```

**Comment by nborie** [comment]
Thanks for the fix and all the explanations... I will finish and polish it in the days to come.

**Comment by mciissee** [comment]
The trick is that the action property of a countdown item is a js script so you can interact with the entire page of the exercise and all the others components of the page since they behave like standard HTML elements so the function document.querySelector() is able to find them.

After you find the c-hint element you can manipulate the properties of the element like you did inside your python scripts. This is what I did when I access and modify the items property. As you can see when you modify the properties of the component the rendering of the component is updated (I suggest you to use the debug mode this is very useful in this case to understand what happen).

This works thanks to the power of Angular framework. As I said before a component in Angular is an encapsulated and self-updatable element so every time a property change I am able to detect the change and re-render the component.

But there is a bad thing with the code I used because I changed the `items` property and 
the confirmation dialog of the component has not been displayed so I hacked the desired behavior of the component. In practice I can prevent this type of issue by detecting the modification of this property and presenting the dialog box if need or by exposing a function in the API of the component but this will make the framework to complex for standard users.

I don't know what you think about this.

**Comment by nborie** [comment]
Setting directly items to be consumed is fair enough...

The teacher-programmer should take this responsibility and this is not that much ugly. He is also aware at the same time how should behave its grader. This is fine for me and it may not be securised (disallow items modifications before dialog box will not produce benefit in my opinion. On the other side , it will disable a lot of use case (including this one)). It is OK like that !

**Comment by nborie** [comment]
One more test. There are just multiplications at this time but it is possible to add different calculation.

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/arithmetic/mental_calculation.pl

In this P.O.C. exercise, the countdown is not reset at each validation. The student fight against the time to validate the most he can do...

**Comment by mciissee** [comment]
What is the question here exactly? I think that I missed something sorry. Did you try to generate  operation different type of operation? If this is what you try to do yes it's possible.

**Comment by nborie** [comment]
No question for now... I just would like to test this component in several ways before inviting you to close this ticket. (I am 95% convinced it could be closed now but I really love certifications...)

To be sure that the component is designed properly, I hope to finalize the last example by adding additions, subtractions, divisions, (a+b)(a-b) = a^2 - b^2, simple powers, powers of 2, etc... I would also like to implement a programing exercise in which your have 5 minutes to set your best answer (like code golf : least character challenge)...

If all these beta testing of count down work, I will be fully convinced that the design is the good one. If I found some problems, I will ask you some support or modification on this ticket. In my last answer, I was just sharing another not ended experimentation with count down...
