### ISSUE TITLE
[Input] Default style

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#24]
With the current default style, the input field is simply underlined. It would be visually better to have it outlined.

Also, I don't understand the default size property. It doesn't seem to be 100% of the parent element.

**Comment by mciissee** [comment]
The default size property can be modified by the teacher using css. if I change the default size to 100% the input will take the entire width of the screen and this will introduce the same problem for teachers which will not want this behavior.

For the underline style this can be done using css also but I agree to change it and make it outlined.

**Comment by mciissee** [comment]
I added new properties like `width` and 'appearance' to let you the possibility to modify the appearance of the component. You can look at the documentation and tell me if it's OK.

You may have to refresh the browser cache few times to get the latest update from the CDN or wait a little.
