### ISSUE TITLE
Add methods in components' Python classes

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#25]
If I'm not mistaken, there's a Python class associated to each type of component.

I'd like to add methods to these Python classes to eventually write PL exercises like that :

~~~
radio=:RadioGroup

before ==
content=["A","B","C","D"]
sol="B"
radio.loadContent(content)
==

evaluator ==
grade = radio.evalByContent(sol)
==
~~~

Is it possible to do that ? How ?

**Comment by mciissee** [comment]
I created an example inside the file **lib/components/custom/customradiogroup.pl**

In the current version to create a custom python class for a component you must create a python class extending Component class and define the `selector` by yourself inside the constructor and a `decorator` property used by the framework to known what class to instantiate.

If decorator is CustomRadio then the class must be named CustomRadio and the python file must be named in lowercase and imported into the sandbox.

Currently you write the following code
```
radio =: RadioGroup
radio.decorator = CustomRadioGroup
```

But for the next version you will write

```
radio =: CustomRadioGroup
```

**Comment by ddoyen** [comment]
Great !

**Comment by mciissee** [comment]
Perfect this one can be closed
