### ISSUE TITLE
[Text] Splitting words

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#26]
In the current version of `Text` component, the text is split on a given separator (a blank space for example). But in a natural language, the word splitting is often more subtle than that. And in some contexts, one could want a syllab splitting, or to make some words not clickable.

Therefore, I suggest to let the possibility to the user to provide a splitting for the text. 

For instance, there could be two attributes to provide the text.
- `plaintext`: plain text, the splitting is left to the component.
- `splittext` : a text where the clickable parts are marked with some pair of delimiters (braces ?)

**Comment by ddoyen** [comment]
I agree that the component should be kept simple.

But I think a splitting along spaces is virtually useless for exercises on french language (and probably on many other languages).

So, if there is only one attribute for the text, this should be imho what I have named `splittext` : a text with braces enclosing selectable units.

Besides, the `free` mode is a good idea ! But it serves a different purpose.

**Comment by mciissee** [comment]
> So, if there is only one attribute for the text, this should be imho what I have named `splittext` : a text with braces enclosing selectable units.

Like I said this is a specific use case solution.  I agree that It will work but I know that some users will ask for more features. An example is that for a large text with many selectable words (maybe all the words) some users will see this solution too difficult.

What I can do is to keep the split mode to provide index based grading and implement the free selection mode to provide content base grading which works on all the cases. In this way the component is simple to use and for me it means no need to maintain it.


If you really want the `splittext` property It can be the default behavior of the component if everyone is agree with that @nborie @nimdanor maybe you can ask the question to teachers that could use it @ddoyen

**Comment by nimdanor** [comment]
This word selection component can be used in a lot of contexts.
Could we for the split mechanism propose a string of splitting characters. This should answer @ddoyen  needs, in a lot of cases. Is this difficult @mciissee ? 

The free mode is excellent (is there an hidden char problem (non printable that are selected ?), my question is how do you make a multiple selection ? does a list of the selected word appear below the text ? How do you undo a selection ? Is there and example i can try ?

**Comment by mciissee** [comment]
> Could we for the split mechanism propose a string of splitting characters. This should answer @ddoyen needs, in a lot of cases. Is this difficult @mciissee ?

The component currently propose a separator property (space by default) that can be changed by the teacher.

> The free mode is excellent (is there an hidden char problem (non printable that are selected ?), my question is how do you make a multiple selection ? does a list of the selected word appear below the text ? How do you undo a selection ? Is there and example i can try ?

The usage of the free mode is exactly like the current mode the difference it that instead of click to select a word you move the mouse to select the text you want like if you want to copy a part of a text. 
For multiple selection if your selection overlap another selection it will remove the overlapped selection. To undo you must click on a selected text. The only default of this mode is that I will not provide index for the selected word for technical reason only the selected text without any invisible char (space, newline...) by using string.trim().

**Comment by ddoyen** [comment]
> This word selection component can be used in a lot of contexts.
> Could we for the split mechanism propose a string of splitting characters. This should answer @ddoyen needs, in a lot of cases. Is this difficult @mciissee ?

I'm not sure french word splitting could be done like that. There is still the problem of punctuation: punctuation mark after a word is not in the word. And there are other cases : exercises where the clickable units are syllabs or groups of words.

That's why I suggest to leave the splitting to the user. Of course, we can write a small library for common splittings.

**Comment by ddoyen** [comment]
It's not the same UX (for the student).

**Comment by mciissee** [comment]
I cannot delegate the splitting to the teacher like a said, written a library for specific use cases require a lot of effort, the component complexity will grow indefinitely and this will delegate all the task to the maintainer of the components for every feature request. If a teacher want to extend the functionality of a component he can use the css API for visual changes or create his own component class like you did for the issue #25 to change the behavior. The teacher can then encapsulate  the code inside a PL template like you did for MathInput and JSXGraph (MathDrawer currently). 

Usually to select a part of a text the end user use the mouse to select the text this is the standard way to selecting text so there is no difference in term of UX the only issue that I can see is on mobile device where selecting is not easy even if I delegate the splitting to the teacher.
