### ISSUE TITLE
Composition of components

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#27]
If i want to "compose" the components, i need to create a template each time ?
I can't use the extends mechanism.

I have a Editor template (pltest) and i want to add the countdown component ? 
I have an exercise  (using the pltest template) and i want to add the countdown component ? 

we need to be able to compose the new component that are independent of each other. 

A new operator ++= ?
A new set of keys form*= (every key that starts with from will do for a part in from) ?
A dic for form ?

Propositions ?

**Comment by mciissee** [comment]
This is not linked to the components.

If you want to add extra content to the `form` key you must use `+= `operator. But currently this operator will not work in the case of an inheritance. B.pl cannot append a content to form key declared in A.pl if B.pl extends A.pl.
