### ISSUE TITLE
[Input] Autocompletion

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#28]
For some exercises, a multiple-choice input field makes the answer too easy to guess while a free text input is too difficult to evaluate.

A text input field with an autocompletion in a given (large) list of choices could offer the best of both worlds.

Here is a demo : https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Languages/testcomp/autocompletion.pl

**Comment by mciissee** [comment]
Did you really want a different component for this? I can introduce new property to the existing input component to provide the same behavior

**Comment by ddoyen** [comment]
No, I thought it could be a new property of `Input`.

**Comment by mciissee** [comment]
Nice I will add the property for the next week.

**Comment by mciissee** [comment]
Implemented so I will close this one
