### ISSUE TITLE
Multi-langage editor

### ISSUE THREAD

**Issue by nborie** [PremierLangage/components#29]
Imagine I want to challenge students with a code golf like the following one :

Write the shortest program ever which read an integer `n` and write on the standard output the `n^{th}` line of Pascal's triangle. For example, if the read integer is `7`, your program should print `1 7 21 35 35 21 7 1` (no need to print a newline character). The choice of programming language is open.

Here is a screenshot from Codewars which allows such kind of multi-language exercise.

![editor_multi_langage](https://user-images.githubusercontent.com/6042616/67637263-f7786e00-f8d8-11e9-95d0-ae4522f09ab5.png)

I am fine with the current editor component. I just would like an editor which can be dynamically reset by the user following a `<select>` drop down list of available language. I think this should be dealt at component level because one does not need the sandbox or any evaluation here. However, the exercise should be updated in terms of input/output.

    editor.langageSelector % true
    editor.langageDefault = python
    editor.langageCode = [ 
    {"langage" : "python", "code" : "n = input()"},
    {"langage" : "C", "code" : "int n; scanf("%d", &n);"},
    {"langage" : "bash", "code" : "read n"},
    ...
    ]

Since the user can be silly and change mind a lot of time, the component should keep in memory all tries in every language (by overwriting default code proposition associated selected language...).

Since stdin, stdout and args are closed to be common in every serious programming languages, this will open the door to multi-language exercises and games. CodinGames propose a similar mechanism for information.

I also must admit that the associated graders are not ready for now... AFAIK only graders in C proceed this way. 

The design of this should be discussed some time between different authors before building a square wheel.

**Comment by mciissee** [comment]
I added new property called `codes` which allow the teacher to add multiple languages and the editor will keep it's state between the change of the languages.

In multiple language mode the property `language` is the selected language and the property `code` is the code of the selected language.

I updated the doc so you can try the example @nborie
