### ISSUE TITLE
[MathDrawer] Cannot change attributes

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#3]
Here is the code (tested with Firefox 68.0.1 and Chromium 76.0.3809.87).

https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/testcomp/stylejsxgraph.pl

~~~
@ /utils/sandboxio.py
grader  =@ /grader/evaluator.py
builder =@ /builder/before.py

drawer =: MathDrawer

drawer.attributes %=
{
    "boundingbox": [
      -6,
      6,
      6,
      -6
    ],
    "showNavigation": false
  }
==

drawer.debug = True

before==
==

title==
Math Drawer Component
==

text==
==

form==
{{ drawer|component }}
==

extrajs==
<script>
    function onMathDrawerReady(component) {
        const board = component.board;
    }
</script>
==

evaluator==
grade = (100, 'Bonne réponse');
==
~~~

**Comment by mciissee** [comment]
here is an example implementing these features : https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/Mathematics/exercises/complex_numbers/affixe.pl

Can you test it on multiple browser and tell me the version of the unsupported browsers ?
