### ISSUE TITLE
[BUG] problème de selection et focus dans l'éditeur du composant edittor

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#35]
**Reproduction**
Quand on valide un exercice et que l'on a un retour (avec un exo pltest).
sur les machines de l'université avec Firfox ESR, 
il y a un comportement qui fait qu'une partie du text dans l'editeur et selectionné et qu'il est difficille d'optenir le focus dans le fichier pour pouvoir corriger le code.

**Comment by mciissee** [comment]
Vous avez un lien vers un exercise illustrant ce problème et/ou un screenshot du bug?
