### ISSUE TITLE
[ENHANCEMENT] i am color blind (matchlist)

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#36]
**Related Component**
Matchlist

**Feature Description**
i you would like to see the difference bitween REd and GREEN .... 

**Use Case**
When i get the answer i can't différenciate between correct and incorrect anwsers 

**Additional Info**

in the user  profile i have said that i was colorblind but it as no effect .

**Comment by mciissee** [comment]
The component does not know anything about PL so it cannot access to the user profile and this is the goal of the component.

The color displayed after the grading is defined by the css classes success-state, warning-state and error-state. You can add your own css to override the colors, create your own classes to meets your need. You can even not use a color to provide grading information which is the standard way of dealing with this type of issues.

**Comment by nimdanor** [comment]
Ok then i need a color change because i can't see the diffrence between the 
red and the green used today. Can i have a doted line for the wrong answers.

**Comment by nimdanor** [comment]
I am working on an type of exercise that uses a CSV  file and the matchlis component,
it's realy disturbing not to be able to see what answers are correct and what answers are incorrect.

**Comment by nimdanor** [comment]
Could on of the links be of light color and the over of deep color.

**Comment by mciissee** [comment]
The colors of the component are now updated
