### ISSUE TITLE
[ENHANCEMENT] button Group

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#39]
**Name and Html Selector**

name => button Group
selector => &lt;c-button-group&gt;&lt;/c-button-group&gt;

**Goal of the Component**
When you click on the button it's a validation.

**Properties of the Component**
Same things as radio ?

**Example**
Not yet

**Dependencies**
?
**Additional Info**
??

**Comment by mciissee** [comment]
Button element is a standard element of HTML 5 API
