### ISSUE TITLE
[Color-blind ENHANCEMENT] Add fail/success icons in radio and checkbox items to display correction

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#41]
**Related Component**
Radio and Checkbox

**Feature Description**

For now, I have displayed correction in radio and checkbox fields with colors. But we are often facing raging complaints from our color-blind users :-)

Therefore, I'd like to supplement this color correction with fail/success icons. Of course, I can add the html code in the `content` attribute of each item. That's what I've implemented in the demo below.

https://pl.u-pem.fr/filebrowser/demo/9868/

However, that does not seem a clean solution to me. It's not a content, it's a style. So, can it be done with CSS only ? Should we add an `icon` attribute ?

**Comment by mciissee** [comment]
The right way to add an icon is the solution you implemented (add an html code that display the icon) because there is a lot of way to display icon in html (font-awesome, src, material-icon...) the icon is not a css it's a part of the component content.
