### ISSUE TITLE
[BUG] Resizing JSXGraph with custom CSS class

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#45]
I still have problems resizing JSXGraph component.

When I try the piece of code below with a custom CSS class, the container is resized to 300px (default is 400px) but the JSXGraph board does not seem to be resized. It is cropped.

~~~
jxg =: MathDrawer

jxg.css = myclass

extracss==
<style>
.myclass {
    max-width: 300px;
    width: 90vw;
    max-height: 300px;
    height: 90vw;
    margin: 0 auto;
}
</style>
==
~~~

However, if I replace directly the default CSS class `jsxgraph-component`, everything is fine. But that is not a good solution. The first piece of code should work.

~~~
jxg =: MathDrawer

extracss==
<style>
.jsxgraph-component {
    max-width: 300px;
    width: 90vw;
    max-height: 300px;
    height: 90vw;
    margin: 0 auto;
}
</style>
==
~~~

Note : Tested with recent versions of Chrome and Firefox.

**Comment by mciissee** [comment]
Can I have a link to the exercise?

**Comment by ddoyen** [comment]
https://pl.u-pem.fr/filebrowser/option?name=test_pl&path=Yggdrasil/demo/jsxgraph/demo_jsxgraph_size.pl

**Comment by mciissee** [comment]
Ok the sandbox seems down. But I think that your first example should work if you add the suffix ```!important``` to the css properties.

E.g. ```max-width: 300px !important;```.

The default css class seems to be more important than the custom classes. Maybe I should invert the priorities if it is possible.

**Comment by ddoyen** [comment]
I tried and it didn't work. Actually, the container is resized, but not the board. You'll see when the sandbox is back.

**Comment by mciissee** [comment]
I tried and effectively the second approach works.
You should use the second approach which is also a good solution since the components css class naming follow a strict coding convention that I use. So your code will always be backward compatible with the future updates.

**Comment by ddoyen** [comment]
And if we need two JSXGraph components with different sizes in the same exercise ? :-)

But that is no emergency.

**Comment by mciissee** [comment]
You can combine the id selector of the component with the class selector like ```#graph_1.jsxgraph-component``` or just use the id #graph_1 selector if you are sure that the id is unique in the page.

Currenlty I didnt add any convention to the id selector but if I decide to change the id of **this component** I will notice you. Currently the id is generated for JSXGrapComponent is just ```graph_N``` where N is the position of the graph on the page starting from 1
