### ISSUE TITLE
Checkboxgroup : Exemple pas assez explicite

### ISSUE THREAD

**Issue by ochampal** [PremierLangage/components#6]
Dans l'évaluator on aimerait savoir comment récupérer les valeurs qui ont été cochées

**Comment by mciissee** [comment]
Oui la documentation n'est pas encore vraiment finie certains composants ne sont pas encore totalement documentés mais je vous suggère de regarder l'exemple suivant https://pl.u-pem.fr/components/simple-usage qui est parfaitement détaillé.

Cela devrait vous permettre de comprendre le fonctionnement des autres composants et si c'est pas le cas je peux vous écrire un code vous montrant comment récupérer les valeurs cochées du checkbox group en attendant que la documentation soit à jour pour le prochain déploiement de PL.
