### ISSUE TITLE
[BUG] radio-group 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#63]
**Reproduction**
In the documentation for radio-group the feedback dosn't work any more.
It only says a plusing "bad answer". 

Is this because a feedback instruction is missing ?

**Comment by mciissee** [comment]
```
@ /utils/sandboxio.py
grader  =@ /grader/evaluator.py
builder =@ /builder/before.py

group =: RadioGroup

# GENERATE A RANDOM QUESTION
before==
import random
import uuid

A = random.randint(0, 10)
B = random.randint(0, 10)
R = str(uuid.uuid4())

# append random false answers to group.items array.
group.items = []
for i in range(4):
    n = random.randint(0, 100)
    while n == A * B:
        n = random.randint(0, 100)
    group.items.append({
        "id": str(uuid.uuid4()), # generate a random id instead of an hardcoded to avoid cheat
        "content": str(n)
    })

# append random right answer to group.items array.
group.items.append({
    "id": R,
    "content": str(A * B)
})

# shuffle the items
random.shuffle(group.items)
==

title = Radio Group Component

text==
Select the result of **{{ A }}** x **{{ B }}**.
==

# PRESENT THE QUESTION TO THE STUDENT
form==
{{ group|component }}
==

# EVALUATE THE STUDENT ANSWER
evaluator==
S = group.selection
score = 0
feedback = '<span class="error-state animated pulse infinite">Bad answer</span>'

for item in group.items:
    item['css'] = ''
    if item['id'] == S:
        if S == R:
            item['css'] = 'success-border'
            score = 100
            feedback = '<span class="success-state animated pulse infinite">Good answer</span>'
        else:
            item['css'] = 'error-border'
    elif item['id'] == R:
        item['css'] = 'success-border animated pulse infinite'

grade = (score, feedback)
==
```

calls to uuid.uuid4() should be casted to an str this is an error in the example

**Comment by nimdanor** [comment]
Marche pas mieux les valeurs correctes n'apparaissent plus en pulse comme avant.
Donc il y a un feedback du grader mais plus du composant.

**Comment by mciissee** [comment]
C'est normal parceque dans le code du composant il n a pas de feedback animation sur cet exemple `item['css'] = 'success-border'` c'est un choix de de l'exemple

**Comment by nimdanor** [comment]
![image](https://user-images.githubusercontent.com/10084549/82048326-c6b12800-96b4-11ea-8795-be1ff2a5e67f.png)

**Comment by nimdanor** [comment]
S = group.selection
score = 0
feedback = '<span class="error-state animated pulse infinite">Bad answer</span>'

for item in group.items:
    item['css'] = ''
    if item['id'] == S:
        if S == R:
            item['css'] = 'success-border animated pulse'
            score = 100
            feedback = '<span class="success-state animated pulse infinite">Good answer</span>'
        else:
            item['css'] = 'error-border'
    elif item['id'] == R:
        item['css'] = 'success-border animated pulse infinite'

grade = (score, feedback)

y a que bad answer qui pulse

**Comment by mciissee** [comment]
`item['css'] = 'error-border'` il n y a pas d'animation

**Comment by nimdanor** [comment]
j'ai mis str(uuu*) sur R et S et cela marche ...

**Comment by nimdanor** [comment]
tu connais https://bleach.readthedocs.io/en/latest/
