### ISSUE TITLE
[BUG] double éditeur problème 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#64]
**Reproduction**
Yggdrasil/ComputerScience/python/AP1-1920/drafts/dominique/bof/beurk.pl

le contenu des editeurs a un comportement bizare ils ne sont pas distincts. 

j'ai trouvé cela sur le web 
https://github.com/Microsoft/monaco-editor/issues/899

**Comment by mciissee** [comment]
Oui j'avais vu le bug c'est à cause du multiple langage. J'ai choisi le type de langage comme uri et donc si 2 éditeurs ont le même langage alors ils partagent le même uri.

**Comment by nimdanor** [comment]
OK, donc il nous faut une URI avec le cid par exemple ?

**Comment by mciissee** [comment]
Non ca ne suffit pas l'uri identifie de manière unique un fichier. Le cid identifie un component et le composant éditeur peut avoir plusieurs langage. Donc si vous choisissez le cid du component comme uri tous les langages de l'éditeur partageront le même état.

Je m'occuperai de la solution maintenant que l'issue est ouverte je ne l'oublierai pas

**Comment by mciissee** [comment]
https://github.com/PremierLangage/components/blob/b271baae9fc89d5ad570f1f78da97dbc5e73cb24/src/app/components/code-editor/code-editor.component.ts#L151 la ligne à modifier

**Comment by mciissee** [comment]
this is a duplicated issue https://github.com/PremierLangage/platon-front/issues/24
