### ISSUE TITLE
Aliases for the Input component

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#9]
I think it would be more intuitive (and shorter) to have some aliases for the Input component.

- TextInput
~~~
component =: TextInput
~~~
would be an alias for
~~~
component =: Input
component.type = text
~~~

- NumberInput
~~~
component =: NumberInput
~~~
would be an alias for
~~~
component =: Input
component.type = number
~~~

**Comment by oobouillot** [comment]
Dear David,

After discussion with @mciissee , maybe a simple behavior would be to only have a TextInput. No NumberInput, or other aliases.

So, if you would like to have some NumberInput in an exercise, you'll have to parse the returned string of your TextInput, depending on the type it would contain (int or float, maybe others). What do you think of this idea? If this behavior is implemented, would you have to modify quite a lot of exercises?

Moreover, I've asked @mciissee the value of a TextInput to be None if nothing is entered in the TextInput. The idea is to force us to test that something has been entered before testing the correctness of the value.

**Comment by ddoyen** [comment]
I agree that a text input combined with a suitable parsing is a good way to handle numeric answers. 

And I don't use Input in my exercises. I use MathInput (which is precisely a formatted text input). So you can change the behavior of Input without fear.

**Comment by mciissee** [comment]
@oobouillot I changed the behavior to the new one you suggested.

You should update your code to cast `textbox.value` to the type you want and don't forget to remove the debug mode before adding the pl in a pltp file.

**Comment by oobouillot** [comment]
Perfect!

I'm agree with @ddoyen  with the name of Input. Like him, I think that the name TextInput would be more suitable than Input...

**Comment by nimdanor** [comment]
I didn't see this and i am not happy with it.

We would like to have a comportement like input() 
if the use dosn't answer the validate button is not activable or ask for an answer in the given field.
You should not have to take this into account in the grader this is useless work for the coder of the evaluator.

**Comment by nimdanor** [comment]
This solves all issues 👍 - standard name, no random value, mandatory input outside the scope of grader

**Comment by mciissee** [comment]
So what should be done for this one?

**Comment by nimdanor** [comment]
What do you think of 
 a TextInput that is under the responsability of the grader.
and a NumberInput that is under the responsability of the front.

**Comment by mciissee** [comment]
I cannot create two separated components I propose the following solution.

I re-add the property `type` which take the values:
- 'number' => any non number or empty input is converted to 0 and number input is converted to float or int before the grader is called except for 0.0 which is converted to 0 because 0.0 does not exists on Javascript. For example if the user type `'djds'` or`'  '` then the `value` property will be set to `0`, if the user the '`0.01`' the property will be set to the float `0.01` and finally '`0.0`' is converted to 0.

- 'text' => the logic of handling the string entered by the student is delegated to the teacher inside the grader .

What do you thinks about this @nimdanor @ddoyen ?

**Comment by mciissee** [comment]
there is also the type `multiline` which will display a textarea instead of input

**Comment by nimdanor** [comment]
Ok pour moi.


Le 17/10/2019 à 14:46, Mamadou Cisse a écrit :

**Comment by ddoyen** [comment]
Ok pour moi aussi.

**Comment by mciissee** [comment]
Ok j'ai changé le comportement du component. Je vais donc fermé cette issue maintenant.
Pour le renommage du component Je pourrais le faire que lors d'un prochain déploiement de pl @ddoyen
